project_id = "pcvdzswbsnpynchniman"

[functions.create-payment]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.calcom-api]
verify_jwt = false

[functions.nylas-api]
verify_jwt = false

[functions.create-custom-payment]
verify_jwt = false

[functions.daisy-chat]
verify_jwt = false
