project_id = "pcvdzswbsnpynchniman"

[functions.create-payment]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.calcom-api]
verify_jwt = false

[functions.nylas-api]
verify_jwt = false

[functions.create-custom-payment]
verify_jwt = false

[functions.daisy-chat]
verify_jwt = false

[functions.retell-token]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.daisy-assistant]
verify_jwt = false

[functions.stripe-connect-account]
verify_jwt = false

[functions.stripe-connect-payment]
verify_jwt = false

[functions.stripe-connect-invoice]
verify_jwt = false

[functions.stripe-connect-webhook]
verify_jwt = false

[functions.create-booking-checkout]
verify_jwt = false

[functions.booking-webhook]
verify_jwt = false

[functions.consume-credits]
verify_jwt = false
